### PR TITLE
feat: change av-* module demo bundle config and scripts

### PR DESCRIPTION
**Pull request by yzydeveloper**
## Description

1. change av-* module  demo bundle config and scripts
2. change demo.config.ts to vite.config.demo.ts
3. add `preview:demo` scripts
4. av-cliper demo static resources use doc-site

### CODE REVIEW

**Comment by hughfenghen** [comment]
@yzydeveloper What is the purpose of this pull request (PR)?

**Comment by yzydeveloper** [comment]
> @yzydeveloper What is the purpose of this PR?

av-cliper demo static resources use doc-site

**Comment by hughfenghen** [comment]
@yzydeveloper 
`build:demo` did encounter some issues. I've now migrated the DEMO build to the docs-site directory for an improved experience. 
I've also removed relevant code under the av-* modules, retaining only the code necessary for running the DEMO for debugging purposes.

**Comment by hughfenghen** [comment]
> av-cliper demo static resources use doc-site

Since the migration was not completed yesterday, there were two sets of test resources at that time.  [doge]

**Comment by yzydeveloper** [comment]
> > av-cliper demo static resources use doc-site
> 
> Since the migration was not completed yesterday, there were two sets of test resources at that time. [doge]

image
Is it a symbolic link? It doesn't work local

**Comment by yzydeveloper** [comment]
Closed ❌

**Pull request closed without merging**
